### ISSUE TITLE
After added this mod lava don't deal damage

### ISSUE THREAD

**Issue by amadin** [tenplus1/ethereal#11] opened 2015-08-05 05:08 UTC
After added ethereal mod lava don't deal damage to player. If i delete ethereal mod then lava deal damage. I tested on last version of ethereal. Server 0.4.12-dev. I modified some other installed mods (but not modified ethereal on local server) but i don't think this reason for this bug. I don't undestand how ethereal can turn off lava damage, but it is.

**Comment by stujones11** [comment] 2015-08-08 15:33
Are you using the 3darmor mod? There was a bug a while back that could cause this, try updating to the current git master and see if that fixes things.

**Comment by amadin** [comment] 2015-08-08 16:01
Sorry i find throuble mod it is https://github.com/BlockMen/hud/ if i delete hud directory of the hunger mod https://forum.minetest.net/viewtopic.php?id=6342 lava deal damage and water flowing. But then i firt time delete only ethereal mod lava begin deal damage too. But now i check twice. Sorry for issue.

**Comment by stujones11** [comment] 2015-08-08 16:17
Aha, I see what the problem is now, the hud mod is overriding the update_armor function without the new dtime parameter. A wee bit naughty but there was probably no cleaner way to do it.

https://github.com/BlockMen/hud/blob/master/legacy.lua#L26

I will work on a fix asap.

**Comment by amadin** [comment] 2015-08-08 16:27
Thanks

**Comment by stujones11** [comment] 2015-08-08 17:12
No problem, I have just merged a pull request that should fix this.

https://github.com/stujones11/minetest-3d_armor/pull/31

**Closed** 2015-09-16 08:03 UTC
